### PR TITLE
Add success callback with json response to show method

### PR DESCRIPTION
**Pull request by vrunoa**
After the PreferencesActivity intent closes, executes a success
callback with a json object with all the preferences as response.

### CODE REVIEW

**Comment by michelkaeser** [comment]
Great, was looking for that! Do I need to change my JS call to the show function or how can I benefit from this?

Nevermind, got it :)

**Comment by peardox** [comment]
A simple Q MaddinXx

Are you using JQuery?

It simplifies AJAX hugely and all you need is a success: function() {} to handle every eventuality

You also want the error: callback - in case you're out of network coverage (try your app with all networks switched off)

**Comment by michelkaeser** [comment]
@peardox I am :) not a JS guru, so writing plain vanilla JS would be hell for me.

btw you can see my app here: https://github.com/MaddinXx/ch.schwingenonline.app/tree/develop - I tried to build it as "modular/adoptable" as possible so it might be interesting for others as well :)

**Comment by vrunoa** [comment]
Just add the success callback on the cordova call of the plugin, for example

<code>navigator.preferences.show("ch.schwingenonline.app.PreferencesActivity",function(prefs){ var color_scheme = prefs.color_scheme; /**\* do something in javascript */    }); </code>

**Comment by macdonst** [comment]
Sorry, I did not see this pull request earlier. Merged now.

**Comment by vrunoa** [comment]
No problem! Thanks

**Pull request merged**
